/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package android.support.graphics.drawable;

public final class R {
    private R() {}

    public static final class attr {
        private attr() {}

        public static final int alpha = 0x7f030027;
        public static final int coordinatorLayoutStyle = 0x7f0300ab;
        public static final int font = 0x7f0300fe;
        public static final int fontProviderAuthority = 0x7f030100;
        public static final int fontProviderCerts = 0x7f030101;
        public static final int fontProviderFetchStrategy = 0x7f030102;
        public static final int fontProviderFetchTimeout = 0x7f030103;
        public static final int fontProviderPackage = 0x7f030104;
        public static final int fontProviderQuery = 0x7f030105;
        public static final int fontStyle = 0x7f030106;
        public static final int fontVariationSettings = 0x7f030107;
        public static final int fontWeight = 0x7f030108;
        public static final int keylines = 0x7f030136;
        public static final int layout_anchor = 0x7f03013b;
        public static final int layout_anchorGravity = 0x7f03013c;
        public static final int layout_behavior = 0x7f03013d;
        public static final int layout_dodgeInsetEdges = 0x7f030169;
        public static final int layout_insetEdge = 0x7f030172;
        public static final int layout_keyline = 0x7f030173;
        public static final int statusBarBackground = 0x7f0301d0;
        public static final int ttcIndex = 0x7f030232;
    }
    public static final class color {
        private color() {}

        public static final int notification_action_color_filter = 0x7f050075;
        public static final int notification_icon_bg_color = 0x7f050076;
        public static final int ripple_material_light = 0x7f050081;
        public static final int secondary_text_default_material_light = 0x7f050083;
    }
    public static final class dimen {
        private dimen() {}

        public static final int compat_button_inset_horizontal_material = 0x7f060050;
        public static final